### ISSUE TITLE
Can't bind to 'ngClass' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by feimosi** [pleerock/ng2-modal#25]
After updating to v.0.0.22 I'm getting the exception listed below. I've tried to analyze the library's code, but with no luck.  The similar error often happens when we forget to import `CommonsModule`, but it seems to be in place. Any ideas?

v.0.0.21 works perfectly fine.
I'm using `angular@2.1.2`

<details>
<summary>Unhandled Promise rejection: Template parse errors:</summary>

```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngClass' since it isn't a known property of 'div'. ("
     #modalRoot
     (keydown.esc)="closeOnEscape ? close() : 0"
     [ERROR ->][ngClass]="{ in: isOpened, fade: isOpened }"
     [ngStyle]="{ display: isOpened ? 'block' : 'none' }"): t@6:5
Can't bind to 'ngStyle' since it isn't a known property of 'div'. (" (keydown.esc)="closeOnEscape ? close() : 0"
     [ngClass]="{ in: isOpened, fade: isOpened }"
     [ERROR ->][ngStyle]="{ display: isOpened ? 'block' : 'none' }"
     (click)="closeOnOutsideClick ? close() : 0""): t@7:5
Can't bind to 'ngIf' since it isn't a known property of 'button'. ("tent" tabindex="0" *ngIf="isOpened">
            <div class="modal-header">
                <button [ERROR ->]*ngIf="!hideCloseButton" type="button" class="close" data-dismiss="modal" [attr.aria-label]="cancelBu"): t@12:24
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("odal-content" tabindex="0" *ngIf="isOpened">
            <div class="modal-header">
                [ERROR ->]<button *ngIf="!hideCloseButton" type="button" class="close" data-dismiss="modal" [attr.aria-label]=""): t@12:16
Can't bind to 'ngIf' since it isn't a known property of 'h4'. ("="close()"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" [ERROR ->]*ngIf="title">{{ title }}</h4>
                <ng-content select="modal-header"></ng-content>
      "): t@13:40
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("abel || 'Close'" (click)="close()"><span aria-hidden="true">&times;</span></button>
                [ERROR ->]<h4 class="modal-title" *ngIf="title">{{ title }}</h4>
                <ng-content select="modal-head"): t@13:16
Can't bind to 'ngIf' since it isn't a known property of 'button'. ("al-footer">
                <ng-content select="modal-footer"></ng-content>
                <button [ERROR ->]*ngIf="cancelButtonLabel" type="button" class="btn btn-default" data-dismiss="modal" (click)="close()"): t@21:24
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("ass="modal-footer">
                <ng-content select="modal-footer"></ng-content>
                [ERROR ->]<button *ngIf="cancelButtonLabel" type="button" class="btn btn-default" data-dismiss="modal" (click)="): t@21:16
Can't bind to 'ngIf' since it isn't a known property of 'button'. ("lt" data-dismiss="modal" (click)="close()">{{ cancelButtonLabel }}</button>
                <button [ERROR ->]*ngIf="submitButtonLabel" type="button" class="btn btn-primary" (click)="onSubmit.emit(undefined)">{{"): t@22:24
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("tn-default" data-dismiss="modal" (click)="close()">{{ cancelButtonLabel }}</button>
                [ERROR ->]<button *ngIf="submitButtonLabel" type="button" class="btn btn-primary" (click)="onSubmit.emit(undefi"): t@22:16
Can't bind to 'ngIf' since it isn't a known property of 'div'. ("g ' + modalClass" (click)="preventClosing($event)">
        <div class="modal-content" tabindex="0" [ERROR ->]*ngIf="isOpened">
            <div class="modal-header">
                <button *ngIf="!hideCloseBut"): t@10:48
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("e() : 0">
    <div [class]="'modal-dialog ' + modalClass" (click)="preventClosing($event)">
        [ERROR ->]<div class="modal-content" tabindex="0" *ngIf="isOpened">
            <div class="modal-header">
    "): t@10:8 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
Can't bind to 'ngClass' since it isn't a known property of 'div'. ("
     #modalRoot
     (keydown.esc)="closeOnEscape ? close() : 0"
     [ERROR ->][ngClass]="{ in: isOpened, fade: isOpened }"
     [ngStyle]="{ display: isOpened ? 'block' : 'none' }"): t@6:5
Can't bind to 'ngStyle' since it isn't a known property of 'div'. (" (keydown.esc)="closeOnEscape ? close() : 0"
     [ngClass]="{ in: isOpened, fade: isOpened }"
     [ERROR ->][ngStyle]="{ display: isOpened ? 'block' : 'none' }"
     (click)="closeOnOutsideClick ? close() : 0""): t@7:5
Can't bind to 'ngIf' since it isn't a known property of 'button'. ("tent" tabindex="0" *ngIf="isOpened">
            <div class="modal-header">
                <button [ERROR ->]*ngIf="!hideCloseButton" type="button" class="close" data-dismiss="modal" [attr.aria-label]="cancelBu"): t@12:24
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("odal-content" tabindex="0" *ngIf="isOpened">
            <div class="modal-header">
                [ERROR ->]<button *ngIf="!hideCloseButton" type="button" class="close" data-dismiss="modal" [attr.aria-label]=""): t@12:16
Can't bind to 'ngIf' since it isn't a known property of 'h4'. ("="close()"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" [ERROR ->]*ngIf="title">{{ title }}</h4>
                <ng-content select="modal-header"></ng-content>
      "): t@13:40
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("abel || 'Close'" (click)="close()"><span aria-hidden="true">&times;</span></button>
                [ERROR ->]<h4 class="modal-title" *ngIf="title">{{ title }}</h4>
                <ng-content select="modal-head"): t@13:16
Can't bind to 'ngIf' since it isn't a known property of 'button'. ("al-footer">
                <ng-content select="modal-footer"></ng-content>
                <button [ERROR ->]*ngIf="cancelButtonLabel" type="button" class="btn btn-default" data-dismiss="modal" (click)="close()"): t@21:24
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("ass="modal-footer">
                <ng-content select="modal-footer"></ng-content>
                [ERROR ->]<button *ngIf="cancelButtonLabel" type="button" class="btn btn-default" data-dismiss="modal" (click)="): t@21:16
Can't bind to 'ngIf' since it isn't a known property of 'button'. ("lt" data-dismiss="modal" (click)="close()">{{ cancelButtonLabel }}</button>
                <button [ERROR ->]*ngIf="submitButtonLabel" type="button" class="btn btn-primary" (click)="onSubmit.emit(undefined)">{{"): t@22:24
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("tn-default" data-dismiss="modal" (click)="close()">{{ cancelButtonLabel }}</button>
                [ERROR ->]<button *ngIf="submitButtonLabel" type="button" class="btn btn-primary" (click)="onSubmit.emit(undefi"): t@22:16
Can't bind to 'ngIf' since it isn't a known property of 'div'. ("g ' + modalClass" (click)="preventClosing($event)">
        <div class="modal-content" tabindex="0" [ERROR ->]*ngIf="isOpened">
            <div class="modal-header">
                <button *ngIf="!hideCloseBut"): t@10:48
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("e() : 0">
    <div [class]="'modal-dialog ' + modalClass" (click)="preventClosing($event)">
        [ERROR ->]<div class="modal-content" tabindex="0" *ngIf="isOpened">
            <div class="modal-header">
    "): t@10:8
```

</details>

**Comment by mcst** [comment]
Same here:

> Unhandled Promise rejection: Template parse errors:
> Can't bind to 'ngClass' since it isn't a known property of 'i'. ("ass="btn btn-outline-primary" id="dropdownMenu2" ngbDropdownToggle><i class="fa" aria-hidden="true" [ERROR ->][ngClass]="{'fa-th-list': arrangedAs('list'), 'fa-th': arrangedAs('table')}" ></i></button>
>   <div c"): ContentComponent@10:112 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:(…) Error: Template parse errors:
> Can't bind to 'ngClass' since it isn't a known property of 'i'. ("ass="btn btn-outline-primary" id="dropdownMenu2" ngbDropdownToggle><i class="fa" aria-hidden="true" [ERROR ->][ngClass]="{'fa-th-list': arrangedAs('list'), 'fa-th': arrangedAs('table')}" ></i></button>
>   <div c"): ContentComponent@10:112
>     at TemplateParser.parse (http://localhost:4200/main.bundle.js:18333:19)
>     at JitCompiler._compileTemplate (http://localhost:4200/main.bundle.js:49600:68)
>     at http://localhost:4200/main.bundle.js:49475:62
>     at Set.forEach (native)
>     at JitCompiler._compileComponents (http://localhost:4200/main.bundle.js:49475:19)
>     at createResult (http://localhost:4200/main.bundle.js:49358:19)
>     at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:90646:26)
>     at Zone.run (http://localhost:4200/main.bundle.js:90528:43)
>     at http://localhost:4200/main.bundle.js:90916:57
>     at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:90679:35)

**Comment by pleerock** [comment]
@mcst are you sue you have this problem with this library? Code your provided does not relate to this library. @feimosi also not sure what is your problem. [There is ngClass](https://angular.io/docs/ts/latest/api/common/index/NgClass-directive.html) directive and it should work fine

**Comment by feimosi** [comment]
@pleerock I'm just saying that after upgrading from v.0.0.21 to v.0.0.22 I'm getting an error. I thought you'd have more insight into the problem.
